In [1]:
import pandas as pd
data = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M',skiprows=1)
df = data[0]
df.columns=['PostalCode','Borough','Neighborhood']
df.head()

  PostalCode           Borough      Neighborhood
0        M2A      Not assigned      Not assigned
1        M3A        North York         Parkwoods
2        M4A        North York  Victoria Village
3        M5A  Downtown Toronto      Harbourfront
4        M6A        North York  Lawrence Heights

In [2]:
df = df[df.Borough != 'Not assigned']
df.head()

  PostalCode           Borough      Neighborhood
1        M3A        North York         Parkwoods
2        M4A        North York  Victoria Village
3        M5A  Downtown Toronto      Harbourfront
4        M6A        North York  Lawrence Heights
5        M6A        North York    Lawrence Manor

In [10]:
df[df['Neighborhood'] == "Not assigned"]

Empty DataFrame
Columns: [PostalCode, Borough, Neighborhood]
Index: []

In [11]:

def replace(row):
    if row['Neighborhood'] == 'Not assigned':
        row['Neighborhood'] = row['Borough']
    return row

df = df.apply(replace, axis = 1)
df.head()

  PostalCode           Borough      Neighborhood
1        M3A        North York         Parkwoods
2        M4A        North York  Victoria Village
3        M5A  Downtown Toronto      Harbourfront
4        M6A        North York  Lawrence Heights
5        M6A        North York    Lawrence Manor

In [12]:
df.head(7)

  PostalCode           Borough      Neighborhood
1        M3A        North York         Parkwoods
2        M4A        North York  Victoria Village
3        M5A  Downtown Toronto      Harbourfront
4        M6A        North York  Lawrence Heights
5        M6A        North York    Lawrence Manor
6        M7A  Downtown Toronto      Queen's Park
8        M9A         Etobicoke  Islington Avenue

In [13]:

df = df.groupby(['PostalCode','Borough']).apply(lambda group: ','.join(group['Neighborhood']))
df = df.to_frame()
df.head()

                                                           0
PostalCode Borough
M1B        Scarborough                         Rouge,Malvern
M1C        Scarborough  Highland Creek,Rouge Hill,Port Union
M1E        Scarborough       Guildwood,Morningside,West Hill
M1G        Scarborough                                Woburn
M1H        Scarborough                             Cedarbrae

In [14]:
df = df.rename(columns = {0: 'Neighborhood'}).reset_index()
df.head()

  PostalCode      Borough                          Neighborhood
0        M1B  Scarborough                         Rouge,Malvern
1        M1C  Scarborough  Highland Creek,Rouge Hill,Port Union
2        M1E  Scarborough       Guildwood,Morningside,West Hill
3        M1G  Scarborough                                Woburn
4        M1H  Scarborough                             Cedarbrae

In [15]:
df.shape

(103, 3)

In [16]:
import pandas as pd
df2 = pd.read_csv('http://cocl.us/Geospatial_data')
df2.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [17]:
df3 = pd.merge(df, df2, left_on = 'PostalCode', right_on = 'Postal Code', how = 'left')
df3

,PostalCode,Borough,Neighborhood,Postal Code,Latitude,Longitude
0,M1B,Scarborough,"Rouge,Malvern",M1B,43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek,Rouge Hill,Port Union",M1C,43.784535,-79.160497
2,M1E,Scarborough,"Guildwood,Morningside,West Hill",M1E,43.763573,-79.188711
3,M1G,Scarborough,Woburn,M1G,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,M1H,43.773136,-79.239476
5,M1J,Scarborough,Scarborough Village,M1J,43.744734,-79.239476
6,M1K,Scarborough,"East Birchmount Park,Ionview,Kennedy Park",M1K,43.727929,-79.262029
7,M1L,Scarborough,"Clairlea,Golden Mile,Oakridge",M1L,43.711112,-79.284577
8,M1M,Scarborough,"Cliffcrest,Cliffside,Scarborough Village West",M1M,43.716316,-79.239476
9,M1N,Scarborough,"Birch Cliff,Cliffside West",M1N,43.692657,-79.264848
10,M1P,Scarborough,"Dorset Park,Scarborough Town Centre,Wexford He...",M1P,43.757410,-79.273304
11,M1R,Scarborough,"Maryvale,Wexford",M1R,43.750072,-79.295849
12,M1S,Scarborough,Agincourt,M1S,43.794200,-79.262029
13,M1T,Scarborough,"Clarks Corners,Sullivan,Tam O'Shanter",M1T,43.781638,-79.304302
14,M1V,Scarborough,"Agincourt North,L'Amoreaux East,Milliken,Steel...",M1V,43.815252,-79.284577
15,M1W,Scarborough,L'Amoreaux West,M1W,43.799525,-79.318389
16,M1X,Scarborough,Upper Rouge,M1X,43.836125,-79.205636
17,M2H,North York,Hillcrest Village,M2H,43.803762,-79.363452
18,M2J,North York,"Fairview,Henry Farm,Oriole",M2J,43.778517,-79.346556
19,M2K,North York,Bayview Village,M2K,43.786947,-79.385975
20,M2L,North York,"Silver Hills,York Mills",M2L,43.757490,-79.374714
21,M2M,North York,"Newtonbrook,Willowdale",M2M,43.789053,-79.408493
22,M2N,North York,Willowdale South,M2N,43.770120,-79.408493
23,M2P,North York,York Mills West,M2P,43.752758,-79.400049
24,M2R,North York,Willowdale West,M2R,43.782736,-79.442259
25,M3A,North York,Parkwoods,M3A,43.753259,-79.329656
26,M3B,North York,Don Mills North,M3B,43.745906,-79.352188
27,M3C,North York,"Flemingdon Park,Don Mills South",M3C,43.725900,-79.340923
28,M3H,North York,"Bathurst Manor,Downsview North,Wilson Heights",M3H,43.754328,-79.442259
29,M3J,North York,"Northwood Park,York University",M3J,43.767980,-79.487262
...,...,...,...,...,...,...
73,M6C,York,Humewood-Cedarvale,M6C,43.693781,-79.428191
74,M6E,York,Caledonia-Fairbanks,M6E,43.689026,-79.453512
75,M6G,Downtown Toronto,Christie,M6G,43.669542,-79.422564
76,M6H,West Toronto,"Dovercourt Village,Dufferin",M6H,43.669005,-79.442259
77,M6J,West Toronto,"Little Portugal,Trinity",M6J,43.647927,-79.419750
78,M6K,West Toronto,"Brockton,Exhibition Place,Parkdale Village",M6K,43.636847,-79.428191
79,M6L,North York,"Downsview,North Park,Upwood Park",M6L,43.713756,-79.490074
80,M6M,York,"Del Ray,Keelesdale,Mount Dennis,Silverthorn",M6M,43.691116,-79.476013
81,M6N,York,"The Junction North,Runnymede",M6N,43.673185,-79.487262
82,M6P,West Toronto,"High Park,The Junction South",M6P,43.661608,-79.464763
83,M6R,West Toronto,"Parkdale,Roncesvalles",M6R,43.648960,-79.456325
84,M6S,West Toronto,"Runnymede,Swansea",M6S,43.651571,-79.484450
85,M7A,Downtown Toronto,Queen's Park,M7A,43.662301,-79.389494
86,M7R,Mississauga,Canada Post Gateway Processing Centre,M7R,43.636966,-79.615819
87,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern,M7Y,43.662744,-79.321558
88,M8V,Etobicoke,"Humber Bay Shores,Mimico South,New Toronto",M8V,43.605647,-79.501321
89,M8W,Etobicoke,"Alderwood,Long Branch",M8W,43.602414,-79.543484
90,M8X,Etobicoke,"The Kingsway,Montgomery Road,Old Mill North",M8X,43.653654,-79.506944
91,M8Y,Etobicoke,"Humber Bay,King's Mill Park,Kingsway Park Sout...",M8Y,43.636258,-79.498509
92,M8Z,Etobicoke,"Kingsway Park South West,Mimico NW,The Queensw...",M8Z,43.628841,-79.520999
93,M9A,Etobicoke,Islington Avenue,M9A,43.667856,-79.532242
94,M9B,Etobicoke,"Cloverdale,Islington,Martin Grove,Princess Gar...",M9B,43.650943,-79.554724
95,M9C,Etobicoke,"Bloordale Gardens,Eringate,Markland Wood,Old B...",M9C,43.643515,-79.577201
96,M9L,North York,Humber Summit,M9L,43.756303,-79.565963
97,M9M,North York,"Emery,Humberlea",M9M,43.724766,-79.532242
98,M9N,York,Weston,M9N,43.706876,-79.518188
99,M9P,Etobicoke,Westmount,M9P,43.696319,-79.532242
100,M9R,Etobicoke,"Kingsview Village,Martin Grove Gardens,Richvie...",M9R,43.688905,-79.554724
101,M9V,Etobicoke,"Albion Gardens,Beaumond Heights,Humbergate,Jam...",M9V,43.739416,-79.588437
102,M9W,Etobicoke,Northwest,M9W,43.706748,-79.594054

In [18]:
df3 = df3.drop(columns = ['Postal Code'])

In [19]:
df3.head()

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge,Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek,Rouge Hill,Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood,Morningside,West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476